classdef StepData < handle
    % Container for zebris plantar pressure data
    
    properties
        Name % Name of step
        Code % Participant ID the step data belongs to
        Pressure % Pressure data [m x n x k] matrix with time along k
        Type
        Begin
        End
        Side
        Heel
        Toe
    end
    
    methods
        function obj = StepData()
            % UNTITLED Construct an instance of this class
            %   Detailed explanation goes here
            
        end
        
        function export2nifti(obj)
            % zebris.StepData.export2nifti - Export pressure data to the NIfTI file format
            
            niftiwrite(obj.Pressure, [obj.Code,'_',obj.Side,'_',obj.Name]);
            
            % adding all the possible metadata to the file (to improve!: adding the time for the quant)
            %             info = niftiinfo('participant1_left1.nii');
            
            %             info.Description = string(fprintf('First_Name: %s', obj.FirstName))...
            %([fprintf('Last_Name: %s', a.s.measurement.patient.last_name.Text)]),...
            %([fprintf('Born: %s', a.s.measurement.patient.born.Text)])];...
            %string(["Sex: ", a.s.measurement.patient.sex.Text]);...
            %string(["Code: ", a.s.measurement.patient.code.Text]);...
            %string(["Type: ", a.s.measurement.type.Text]);...
            %string(["Program: ", a.s.measurement.type.Text]);...
            %string(["Program_Version: ", a.s.measurement.program_version.Text]);...
            %string(["Measured: ", a.s.measurement.measured.Text]);...
            %string(["Description: ", a.s.measurement.description.Text])];
            
            %%%%%%%%%%%%% Max. 80 characters! %%%%%%%%%%%%%%
            %             info.Description = [...
            %                 'First_Name: ',obj.FirstName,'; ',...
            %                 'Last_Name: ',obj.LastName,'; ',...
            %                 'Born: ',obj.Born,'; ',...
            %                 'Sex: ',obj.Sex,'; ',...
            %                 'Code: ',obj.Code,'; ',...
            %                 'Type: ',obj.Type,'; ',...
            %                 'Program: ',obj.Program,'; ',...
            %                 'Program_Version: ',obj.ProgramVersion,'; ',...
            %                 'Measured: ',obj.Measured,'; ',...
            %                 'Description: ',obj.Description];
            %             niftiwrite(obj.Pressure, 'participant1_left1.nii', info);
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %
            %             info = niftiinfo('participant1_left1.nii');
        end
    end
end